/**
 * agent-chaperone public entry point.
 *
 * Today this exposes the transparent proxy. The screens, the policy engine and
 * the audit log attach to the proxy's event seam as they land. See
 * docs/design.md for the architecture and ROADMAP.md for the order.
 */

export const PACKAGE_NAME = 'agent-chaperone';

export {
  createProxy,
  spawnUpstream,
  inspect,
  RequestCorrelator,
  LineBuffer,
  LineTooLongError,
  UpstreamStartError,
  DEFAULT_MAX_LINE_BYTES,
  DEFAULT_MAX_PENDING,
  DEFAULT_MAX_PENDING_BYTES,
  frame,
} from './proxy/index.js';
export {
  MODES,
  PolicyError,
  assessSeverity,
  decidePostResult,
  decidePreCall,
  defaultPolicy,
  parsePolicy,
  policyForServer,
  policySchema,
  shouldScreen,
} from './policy/index.js';
export type {
  CorrelatorOptions,
  Direction,
  Envelope,
  EnvelopeKind,
  Gate,
  GateVerdict,
  JsonRpcId,
  PendingRequest,
  ProxyEvent,
  ProxyHandle,
  ProxyOptions,
  ProxyStreams,
  Upstream,
} from './proxy/index.js';
export type {
  CallAction,
  CallAnswers,
  CallReason,
  CallRuleFindings,
  CallThresholds,
  Decision,
  Mode,
  Policy,
  ResultAction,
  ResultAnswers,
  ResultRuleFindings,
  ResultThresholds,
  ScoreAnswer,
  ServerPolicy,
  SeverityAssessment,
  SeverityLabel,
} from './policy/index.js';

export {
  DANGEROUS_PATTERNS,
  DEFAULT_MAX_BLOCKS,
  DEFAULT_MAX_BLOCK_CHARS,
  SECRET_KINDS,
  SECRET_PATTERNS,
  collectStrings,
  findDangerousForms,
  findHiddenInText,
  findHiddenRegions,
  findSecrets,
  firstMatch,
  inspectResult,
  inspectToolCall,
  matchesGlob,
  placeholder,
  redactJson,
  redactText,
  splitIntoBlocks,
} from './rules/index.js';
export type {
  Block,
  CallInspectionInput,
  DangerousMatch,
  DangerousPattern,
  HiddenKind,
  HiddenRegion,
  ResultInspection,
  ResultInspectionInput,
  SecretKind,
  SecretMatch,
  SecretPattern,
  SplitResult,
  ToolCallInspection,
} from './rules/index.js';

export {
  DEFAULT_MAX_RETRIES,
  DEFAULT_TIMEOUT_MS,
  DEFAULT_TOTAL_TIMEOUT_MS,
  MAX_MESSAGE_CHARS,
  RecordingMismatchError,
  TYPESAFE_API_KEY_ENV,
  UnknownRequestError,
  answered,
  createFakeBackend,
  createTypeSafeBackend,
  failure,
  hasTypeSafeKey,
  recordingFor,
  requestHash,
  safeLabel,
  sanitizeMessage,
  validateAnswers,
  validateBattery,
} from './backends/index.js';
export type {
  Answer,
  AnswerFor,
  AnsweredResult,
  AnswersFor,
  AskOptions,
  AskRecord,
  Backend,
  BackendFailure,
  BackendResult,
  Battery,
  ChoiceQuestion,
  Exchange,
  FailedResult,
  FakeBackend,
  FakeEntry,
  NoulQuestion,
  Question,
  Recording,
  ScoreQuestion,
  TypeSafeBackendOptions,
  Validation,
} from './backends/index.js';

export {
  CALL_SEVERITY,
  DEFAULT_MAX_STATE_CHARS,
  DESTRUCTIVE,
  EXFILTRATION,
  EXPOSES_SECRET,
  INSTRUCTS_READER,
  NO_BLOCK,
  OFF_TASK,
  POLICY_VIOLATION,
  POSTRESULT_MEASURED,
  PRECALL_MEASURED,
  RESULT_SEVERITY,
  SECRET_IN_ARGS,
  buildPostResultScreens,
  buildPreCallScreen,
  chunkBlocks,
  mergeResultAnswers,
  readCallAnswers,
  readResultAnswers,
  whichBlock,
} from './screens/index.js';
export type {
  PostResultInput,
  PostResultScreen,
  PostResultState,
  PostResultTool,
  PreCallInput,
  PreCallScreen,
  PreCallState,
  PreCallTool,
  StateHiddenRegion,
} from './screens/index.js';

export {
  RESOURCE_READ,
  TOOL_CALL,
  annotated,
  blockedCall,
  createScreeningGate,
  heldCall,
  quarantined,
  readResultText,
  readToolCall,
  toolError,
  withText,
} from './screening/index.js';
export type {
  BackendUsage,
  CallJudgment,
  Judgment,
  ResultJudgment,
  ResultShape,
  ResultText,
  ScreeningOptions,
  ToolCall,
} from './screening/index.js';

export {
  DIRECTORY_MODE,
  FILE_MODE,
  PRICE_PER_MTOK,
  costOf,
  createAuditLog,
  currentSession,
  findRecord,
  formatRecord,
  parseRecords,
  readRecords,
  sessionFileName,
  sessionFiles,
  sessionPath,
  sessionsDirectory,
  stateDirectory,
  toRecord,
} from './audit/index.js';
export type {
  AuditContent,
  AuditLog,
  AuditLogOptions,
  AuditRecord,
  RecordOptions,
} from './audit/index.js';

export {
  APPROVALS_DIRECTORY,
  DEFAULT_TTL_MS,
  approvalsDirectory,
  callFingerprint,
  grantApproval,
  sweepApprovals,
  takeApproval,
} from './approvals/index.js';
export type { Approval, GrantOptions, TakeOptions } from './approvals/index.js';
